services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: contracts-backend
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      RUN_MODE: ${RUN_MODE}
      FRONTEND_URL: http://localhost:5173
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./backend:/app
      - ./backend/db:/app/db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: contracts-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules